### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Pakuss1337** [isivisi/pybot#50]
Hi, so basically i tried setting up this bot on 3 different platforms (kali, ubuntu 20.04, win11) and every single one gives me the error:
```
Starting main pybot process...
PYBOT BETA VERSION 0 BUILD 121
[pybot.irc] LENGTH.PY PROFANITY.PY REPETITION.PY UPPERCASE.PY WEBSITES.PY  filters loaded
[pybot.irc] IRC object initialized, starting ping check...
[pybot.tornado.web] Web services starting on port 8888
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/Twitch_Pybot-0.1.4-py3.5.egg/pybot/web/pybot_web.py", line 174, in startWebService
    app.listen(int(globals.settings.config['web']['port']))
  File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/usr/local/lib/python3.5/site-packages/tornado/tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "/usr/local/lib/python3.5/site-packages/tornado/tcpserver.py", line 166, in add_sockets
    sock, self._handle_connection
  File "/usr/local/lib/python3.5/site-packages/tornado/netutil.py", line 246, in add_accept_handler
    io_loop = IOLoop.current()
  File "/usr/local/lib/python3.5/site-packages/tornado/ioloop.py", line 263, in current
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.5/asyncio/events.py", line 678, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/local/lib/python3.5/asyncio/events.py", line 584, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-8'.
```
Any solution to this?
I installed it with `python3.5 -m pip install twitch-pybot`, all the dependencies have been successfully installed, so this shouldn't be the problem.

**Comment by isivisi** [comment]
There seems to be caused by Torando > 5, the program was designed when python 3.5 and tornado 4.3 were the latest. I've fixed the PyPI requirements to reflect this for now. I will be looking into getting the latest dependency versions working sometime in the future :)
